
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-test
spec:
  selector:
      matchLabels:
        app: react-test
  replicas: 1
  template:
      metadata:
        labels:
            app: react-test
      spec:
        containers:
        - name: react-test
          image: spreadregistry.azurecr.io/react-test:v1
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"