
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-test
spec:
  selector:
      matchLabels:
        app: react-test
  replicas: 2
  template:
      metadata:
        labels:
            app: react-test
      spec:
        containers:
        - name: react-test
          image: spreadregistry.azurecr.io/react-test
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"